import type { Timestamp } from "firebase/firestore";

export type Ingredient = {
  /** Firestore doc id; absent for raw seed data before it's been inserted. */
  id?: string;
  name: string;
  /** e.g. "lb", "oz", "each", "bunch", "qt", "gal" */
  unit: string;
  /** USD per `unit`, before trim loss is applied. */
  currentCost: number;
  /** Fraction in [0, 1) representing loss during trimming/prep. */
  trimLoss: number;
};

export type InventoryStatus = "active" | "spoiled" | "expired";

export type InventoryItem = {
  /** Firestore doc id; absent before insert. */
  id?: string;
  /** References ingredients/{id} from the shared catalog. */
  ingredientId: string;
  /** Snapshot of the ingredient's name at add-time. */
  itemName: string;
  quantity: number;
  unit: string;
  costPerUnit: number;
  supplier: string;
  dateReceived: Timestamp;
  expiryDate?: Timestamp | null;
  status: InventoryStatus;
  createdAt?: Timestamp;
  updatedAt?: Timestamp;
};

export type CostHistoryEntry = {
  id?: string;
  ingredientId: string;
  date: Timestamp;
  costPerUnit: number;
  supplier: string;
  quantity: number;
  notes?: string;
};

export type WasteLogEntry = {
  id?: string;
  ingredientId: string;
  itemName: string;
  quantity: number;
  unit: string;
  reason: string;
  date: Timestamp;
  costImpact: number;
  notes?: string;
};

export type InvoiceStatus = "pending_review" | "confirmed" | "rejected";

export type InvoiceLineItem = {
  itemName: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  lineCost: number;
  notes?: string;
};

export type Invoice = {
  id?: string;
  /** Original uploaded filename, for display. */
  fileName: string;
  /**
   * Cloud Storage OBJECT PATH (e.g. "restaurants/{id}/invoices/169..._sysco.pdf"),
   * NOT a public download URL. A getDownloadURL() token is a standing bearer
   * credential independent of security rules — resolve a fresh viewing URL
   * on demand via getInvoiceViewUrl() in src/lib/storage.ts instead.
   */
  storageUrl: string;
  supplier: string;
  invoiceDate?: Timestamp | null;
  total?: number | null;
  /** Verbatim transcription from Claude Vision, kept for audit/debugging. */
  rawOcrText: string;
  status: InvoiceStatus;
  lineItems: InvoiceLineItem[];
  parsedErrors?: string[];
  createdAt?: Timestamp;
  reviewedAt?: Timestamp | null;
  reviewedBy?: string | null;
};

export type RecipeStatus = "active" | "superseded";

/**
 * The chunk-7 rating/versioning fields on a saved recipes/{recipeId} doc.
 * Shared here so RecipesList.tsx, GenerateRecipeForm.tsx, and any other
 * reader agree on shape/defaults — the recipe's core content fields
 * (name, ingredients, instructions, cost, etc.) are left to each call site,
 * since they were already established before this chunk (chunk 2/6.1).
 */
export type RecipeVersionFields = {
  version: number;
  /** v1's own doc id; null on v1 itself. */
  baseRecipeId: string | null;
  status: RecipeStatus;
  /** 0-5, shared across the whole v1/v2/... lineage — see chunk 7 plan. */
  aggregateRating: number;
  ratingCount: number;
  lastRatedAt: Timestamp | null;
  /** Only present on v2+, generated by the improveRecipe Cloud Function. */
  changesSummary?: string[];
};

/** The fixed vocabulary of "what went wrong" checkboxes on RecipeRatingModal. */
export const RECIPE_FEEDBACK_ISSUES = [
  "tasted bad",
  "wrong texture",
  "took too long",
  "cost was off",
  "ingredient substitution failed",
  "technique too complex",
  "other",
] as const;
export type RecipeFeedbackIssue = (typeof RECIPE_FEEDBACK_ISSUES)[number];

/** recipes/{recipeId}/feedback/{feedbackId} — see chunk 7. Append-only. */
export type RecipeFeedback = {
  id?: string;
  rating: number;
  taste?: number;
  texture?: number;
  executionTime?: number;
  costAccuracy?: number;
  wouldMakeAgain: boolean;
  issues: RecipeFeedbackIssue[];
  /** Plain text for now — Whisper transcription deferred past MVP. */
  voiceNote?: string;
  createdAt?: Timestamp;
  createdBy: string;
};

/** restaurants/{restaurantId}/ingredientRatings/{ratingId} — see chunk 7. */
export type IngredientRating = {
  id?: string;
  /** References ingredients/{id} from the shared catalog. */
  ingredientId: string;
  taste: number;
  texture: number;
  priceToQuality: number;
  performance: string;
  supplier: string;
  comparison?: {
    comparedTo: string;
    winner: "this" | "other" | "tie";
  };
  notes?: string;
  createdAt?: Timestamp;
  createdBy: string;
};

/**
 * restaurants/{restaurantId}/ingredientIntelligenceCache/{ingredientId} —
 * written only by the aggregateIngredientIntelligence Cloud Function.
 */
export type IngredientIntelligenceCache = {
  lastUpdated?: Timestamp;
  ratingCount: number;
  /** Mean of taste and texture across all ratings (see chunk 7 plan). */
  averageRating: number;
  priceToQuality: number;
  topPerformances: { text: string; voteCount: number }[];
  comparisons: {
    comparedTo: string;
    thisWins: number;
    otherWins: number;
    ties: number;
    preferenceRatio: number;
  }[];
};
